language: java
before_deploy:
  - mv ./build/libs/*.jar ./jar
  - cd ./jar
  - rm -rf ./*-sources-dev.jar
  - rm -rf ./*-dev.jar
  - rm -rf ./*-sources.jar
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
after_deploy:
  - cd ..
install: skip
before_script:
  - rm -rf ./build
script:
  - ./gradlew build
os: linux
