language: java
before_deploy:
  - mv ./build/libs/*.jar ./jar
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file_glob: true
  file: jar/*
after_deploy:
  - rm -rf ./build
install: skip
before_script:
  - rm -rf ./build
script:
  - ./gradlew build
os: linux
